# Generated by Django 4.1.5 on 2023-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
